=== ChebbiAngham/Jubula/org.eclipse.jubula.toolkit.common/resources/xml/ToolkitComponentConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xs:include schemaLocation="CommonComponentConfiguration.xsd" />
	<xs:element name="compSystem">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="configVersion" />
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="abstractComponent" />
                    <xs:element ref="concreteComponent" />
					<xs:element ref="toolkitComponent" />
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="configVersion">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="majorVersion" />
				<xs:element ref="minorVersion" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="majorVersion" type="xs:string" />
	<xs:element name="minorVersion" type="xs:string" />
	<xs:element name="toolkitComponent">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="realizes" />
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="extends" />
				<xs:element ref="testerClass" />
				<xs:element minOccurs="0" maxOccurs="1" ref="componentClass" />
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="action" />
			</xs:sequence>
			<xs:attribute name="type" use="required" type="xs:ID" />
			<xs:attribute name="descriptionKey" use="optional" type="xs:string" />
			<xs:attribute name="visible" default="true" type="xs:boolean" />
			<xs:attribute name="hasDefaultMapping" default="false" type="xs:boolean" />
			<xs:attribute name="observable" default="true" type="xs:boolean" />
			<xs:attribute name="changed" use="optional"/>
			<xs:attribute name="deprecated" default="false" type="xs:boolean" />
            <xs:attribute name="since" use="optional" type="xs:string" />
            <xs:attribute name="supported" default="true" type="xs:boolean" />
		</xs:complexType>
	</xs:element>
	<xs:element name="abstractComponent">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="realizes" />
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="extends" />
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="action" />
			</xs:sequence>
			<xs:attribute name="type" use="required" type="xs:ID" />
			<xs:attribute name="descriptionKey" use="optional" type="xs:string" />
			<xs:attribute name="visible" default="true" type="xs:boolean" />
			<xs:attribute name="changed" use="optional"/>
			<xs:attribute name="deprecated" default="false" type="xs:boolean" />
            <xs:attribute name="since" use="optional" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="testerClass" type="xs:string" />
	<xs:element name="componentClass">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="property" />
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="property">
		<xs:complexType>
			<xs:attribute name="name" use="required" type="xs:string" />
			<xs:attribute name="value" use="required" type="xs:string" />
		</xs:complexType>
	</xs:element>
    <xs:element name="concreteComponent">
	    <xs:complexType>
	        <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="realizes" />
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="extends" />
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="action" />
            </xs:sequence>
	      <xs:attribute name="type" use="required" type="xs:ID"/>
	      <xs:attribute name="descriptionKey" use="optional" type="xs:string" />
	      <xs:attribute name="visible" default="true" type="xs:boolean" />
	      <xs:attribute name="hasDefaultMapping" default="false" type="xs:boolean" />
	      <xs:attribute name="changed" use="optional"/>
	      <xs:attribute name="deprecated" default="false" type="xs:boolean" />
          <xs:attribute name="since" use="optional" type="xs:string" />
	    </xs:complexType>
    </xs:element></xs:schema>

=== ChebbiAngham/Jubula/org.eclipse.jubula.toolkit.rcp.provider/resources/xml/ComponentConfiguration.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
    Copyright (c) 2004, 2010 BREDEX GmbH.
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
 -->
<compSystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../org.eclipse.jubula.toolkit.common/resources/xml/ToolkitComponentConfiguration.xsd">
	<configVersion>
		<majorVersion>2</majorVersion>
		<minorVersion>1</minorVersion>
	</configVersion>
 
    <toolkitComponent type="org.eclipse.ui.internal.views.properties.tabbed.view.TabbedPropertyList" visible="false">
        <realizes>guidancer.concrete.List</realizes>
        <testerClass>org.eclipse.jubula.rc.common.tester.ListTester</testerClass>
        <componentClass name="org.eclipse.ui.internal.views.properties.tabbed.view.TabbedPropertyList" />
    </toolkitComponent>
</compSystem>
